[workspace]
authors = ["zuble <67658465+zuble@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "bcd"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
ipdb = ">=0.13.13,<0.14"

[pypi-dependencies]
pytest-playwright = ">=0.7.2, <0.8"
rich = ">=14.2.0, <15"
